# Generated by Django 3.0.11 on 2021-03-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Google Meet', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'tentative'), (1, 'cancelled'), (2, 'Confirmed')], default=0, max_length=500),
            preserve_default=False,
        ),
    ]
