# Generated by Django 3.0.11 on 2021-03-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20210303_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.CharField(max_length=500),
        ),
    ]
