# Generated by Django 3.1.7 on 2021-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_auto_20210304_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(default='Technical Club of NITK', max_length=500),
            preserve_default=False,
        ),
    ]
